### ISSUE TITLE
The example in the "UI.Next Client-Server Application with Suave" template 403s when calling RPC functions

### ISSUE THREAD

**Issue by tehcrashxor** [intellifactory/websharper.templates#6]
I created a project with the *UI.Next Client-Server Application with Suave* template with no changes from the default files nor settings, compiled, and ran it.  The page displays, but clicking the Send button causes requests which fail in 403s.

<img width="769" alt="403s" src="https://cloud.githubusercontent.com/assets/3751389/18228730/ee87778a-720f-11e6-8bd0-9aaec39a6d7e.png">

**Comment by Tarmil** [comment]
Indeed, [this is a known issue](https://github.com/intellifactory/websharper/issues/603) with the CSRF token which has been fixed in WebSharper; I will publish the fix to NuGet tomorrow. In the meantime you can call `WebSharper.Web.Remoting.DisableCsrfProtection()` just before starting the Suave server to disable anti-CSRF protection on RPCs.

**Comment by tehcrashxor** [comment]
Yep, that works.   Thanks.
